/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useScroll, useTexture, useVideoTexture } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { Color, MeshBasicMaterial, MeshStandardMaterial, SRGBColorSpace } from "three";
import { motion } from "framer-motion-3d";
export function BackGroundModel_3(props) {

  const {section, device} = props;

  const { nodes, materials } = useGLTF("/Scene_1_model_v04.glb");
  const texture1 = useVideoTexture("/cancle_stick_animation_lowRes.mp4");
  const texture2 = useVideoTexture("/market_ticker0001-0599_lowRes.mp4");

  const wallTexture = useTexture("/shadow-shadow_alpha.png")
  wallTexture.flipY = false;
  wallTexture.colorSpace = SRGBColorSpace;


  const wallMaterial = new MeshBasicMaterial({
    map: wallTexture,
    transparent: true,
    opacity: 1,
  });


  const groupRef = useRef();
  const topScl = device==='web'?1:0.9;

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh
        position={[device==='web'?0:-0.2, device==='web'?0:0.03, 0]}
        scale={[topScl, topScl, topScl]}
        geometry={nodes.wall_horizontal.geometry}
        material={wallMaterial}
      />
      <group position={[device==='web'?-0.577:-0.677, 0.478, 0.476]} scale={[topScl, topScl, topScl]}>
        <mesh

          geometry={nodes.Circle003.geometry}
          material={materials["Material.064"]}
        />
        <mesh

          geometry={nodes.Circle003_1.geometry}
          material={materials.text_material}
        />
        <mesh

          geometry={nodes.Circle003_2.geometry}
          material={materials["Material.037"]}
        />
      </group>
      <motion.group
        scale={[1, 1, 1]}
        animate={{
          scale: section === 0 ? [0,1.1,1] : [1,1.1,0],
          transition: { duration: section === 0 ? 1 : 0.6,times: section === 0 ? [0,0.7,1] : [0,0.3,1]},
         
        }}

        position={[-0.577, 0.521, 0.476]}>
        <mesh

          geometry={nodes.ergonomic_chair001.geometry}
          material={materials["Material.038"]}
          position={[0.001, -0.092, -0.113]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh

          geometry={nodes.floor.geometry}
          material={wallMaterial}
          position={[0.577, -0.521, -0.476]}
        />
        <group position={[-0.234, 0.241, -0.51]}>
          <mesh

            geometry={nodes.Plane007.geometry}
            material={materials["Material.039"]}
          />
          <mesh

            geometry={nodes.Plane007_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[0.319, 0.241, -0.53]}>
          <mesh

            geometry={nodes.Plane003.geometry}
            material={materials["Material.012"]}
          />
          <mesh

            geometry={nodes.Plane003_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[0, -0.495, 0]}>
          <mesh

            geometry={nodes.Circle001.geometry}
            material={materials["Material.064"]}
          />
          <mesh

            geometry={nodes.Circle001_1.geometry}
            material={materials.text_material}
          />
          <group position={[1.307, 0.524, -0.969]}>
            <mesh

              geometry={nodes.Circle016.geometry}
              material={materials.monitor_shell}
            />
            <mesh

              geometry={nodes.Circle016_1.geometry}
              material={materials["Material.008"]}
            />
          </group>
          <mesh

            geometry={nodes.screen_1.geometry}
            material={materials.screen_1_mat}
            position={[-0.695, 1.114, -0.683]}
            rotation={[-0.172, 0.496, 0.082]}
            scale={[0.817, 0.778, 1.2]}
          >
            <meshStandardMaterial
              map={texture1}
              emissiveMap={texture1}
              emissive={new Color(1, 1, 1)}
              emissiveIntensity={0.4}
              toneMapped={false}
            />
          </mesh>
          <mesh

            geometry={nodes.screen_2.geometry}
            material={materials.screen_2_mat}
            position={[0.253, 1.114, -0.917]}
            rotation={[-0.151, 0, 0]}
            scale={[0.817, 0.778, 1.2]}
          >
            <meshStandardMaterial
              map={texture2}
              emissiveMap={texture2}
              emissive={new Color(1, 1, 1)}
              emissiveIntensity={0.4}
              toneMapped={false}
            />
          </mesh>
        </group>
      </motion.group>
    </group>
  );
}



useGLTF.preload("/Scene_1_model_v04.glb");
